configName: pic32mz_ef_sk_sw
folderName: ''
format_version: v1.0
frameworkPath: ../../..
processor: PIC32MZ2048EFM144
projectName: ''
settings:
  PackageFilter: bootloader;bootloader_apps_uart;bsp;core;core_apps_pic32mz_ef;crypto;cryptoauthlib;cryptoauthlib_apps;crypto_apps_encrypt_decrypt;csp;csp_apps_pic32mz_ef;net;quick_docs;usb
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: OVERWRITE
  DFPPath: .\dev_packs\Microchip\PIC32MZ-EF_DFP\1.3.57\atdf\PIC32MZ2048EFM144.atdf
