configName: pic32mz_ef_sk_sw
folderName: ''
format_version: v1.0
frameworkPath: ../../..
processor: PIC32MZ2048EFG100
projectName: ''
settings:
  PackageFilter: bootloader;bootloader_apps_sdcard;bootloader_apps_uart;bootloader_apps_usb;bsp;core;core_apps_pic32mz_ef;crypto;cryptoauthlib;cryptoauthlib_apps;crypto_apps_encrypt_decrypt;crypto_apps_large_hash;crypto_apps_speed_test;csp;csp_apps_pic32mz_ef;gfx;gfx_apps_pic32mz_ef;MPLAB-Harmony-Reference-Apps;quick_docs;touch;touch_apps;usb;usb_apps_device;usb_apps_dual_role;usb_apps_host;usb_apps_multi_controller;x2c
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32MZ-EF_DFP\1.3.58\atdf\PIC32MZ2048EFG100.atdf
